export const Users = [
  {
    id: 1,
    profilePicture: "assets/download/profile/1.jpeg",
    username: "Guna",
  },
  {
    id: 2,
    profilePicture: "assets/download/profile/2.jpeg",
    username: "Sivarama Krishnan",
  },
  {
    id: 3,
    profilePicture: "assets/download/profile/3.jpeg",
    username: "Subash",
  },
  {
    id: 4,
    profilePicture: "assets/download/profile/4.jpeg",
    username: "Prem",
  },
  {
    id: 5,
    profilePicture: "assets/download/profile/5.jpeg",
    username: "Royal",
  },
  {
    id: 6,
    profilePicture: "assets/download/profile/6.jpeg",
    username: "Gowtham",
  },
  {
    id: 7,
    profilePicture: "assets/download/profile/7.jpeg",
    username: "Hari Haran",
  },
  {
    id: 8,
    profilePicture: "assets/download/profile/8.jpeg",
    username: "Vairavel",
  },
  {
    id: 9,
    profilePicture: "assets/download/profile/9.jpeg",
    username: "Ravi",
  },
  {
    id: 10,
    profilePicture: "assets/download/profile/10.jpeg",
    username: "Karthi",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/download/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/download/post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/download/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/download/post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/download/post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/download/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/download/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/download/post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/download/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/download/post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
